version: "3"
services:
    PostgreSQL:
        container_name: Postgres-SQL
        image: "postgres:latest"
        hostname: 'postgres-srv'

        # Set admin username and password
        environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=":~D,(A~B?r~1A2ISV<In"

        volumes:
        # Script for initializing the database and users
        - /Docker/Postgres/Scripts/Init.sh:/docker-entrypoint-initdb.d/Init.sh
        # Configurationfile of postgreSQL
        - /Docker/Postgres/Scripts/postgresql.conf:/etc/postgresql/postgresql.conf
        # Volume to store the database data
        - /Docker/Postgres/Volumes/Data:/var/lib/postgresql/data

        networks:
            # Backend network with static ip
            InternalNetwork:
                ipv4_address: 192.168.0.10
            
    
    GitLab:
        container_name: GitLab-SRV
        image: "gitlab/gitlab-ce:latest"
        restart: always
        hostname: 'gitlab-srv'

        environment:
            GITLAB_OMNIBUS_CONFIG: |
                # Whitelisted url
                external_url 'http://192.168.10.66'
                # root password
                gitlab_rails['initial_root_password'] = 'Test1234'
                # PostgreSQL database configuration
                postgresql['enable'] = false
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'unicode'
                gitlab_rails['db_database'] = 'gitlab'
                gitlab_rails['db_password'] = 'oIwhR58Z0spnnez0Ouhj'
                gitlab_rails['db_host'] = '192.168.0.10'
                gitlab_rails['db_port'] = 5432
        
        volumes:
        # Persistent Data; Logs; Configs
        - /Docker/GitLab/Volumes/Config:/etc/gitlab
        - /Docker/GitLab/Volumes/Logs:/var/log/gitlab
        - /Docker/GitLab/Volumes/Data:/var/opt/gitlab
        
        ports:
        - "8082:80"
        
        networks:
            # Backend
            InternalNetwork:
                ipv4_address: 192.168.0.30
            # Frontend
            default:
        
        # Container starts after PostgreSQL
        depends_on:
        - PostgreSQL
        
    
    nextcloud:
        container_name: Nextcloud
        build:
            context: ./../Nextcloud
            dockerfile: Dockerfile
        
        # Save Data and Configs on volumes
        volumes:
        - /Docker/Nextcloud/Volumes/Data:/Nextcloud
        - /Docker/Nextcloud/Volumes:/var/www/html
        
        ports:
        - "8080:80"
        - "8081:443"
        
        networks:
            # Backend
            InternalNetwork:
                ipv4_address: 192.168.0.20
            # Frontend
            default:
        
        # Starts after PostgreSQL
        depends_on:
        - PostgreSQL
        
        
    # Only for datatbase testing
    # pt:
        # container_name: pt
        # image: "postgres:latest"
        # environment:
        # - POSTGRES_USER=root
        # - POSTGRES_PASSWORD=":~D,(A~B?r~1A2ISV<In"
        # volumes:
        # - /Docker/Postgres/Scripts/Init.sh:/docker-entrypoint-initdb.d/Init.sh
        # - /Docker/Postgres/Scripts/postgresql.conf:/etc/postgresql/postgresql.conf
        # # - /Docker/Postgres/Volumes/Data:/var/lib/postgresql/data
        # networks:
        # InternalNetwork:
            # ipv4_address: 192.168.0.40
        # default:
        
    
networks:
    # Backend network definition
    InternalNetwork:
        driver: bridge
        ipam:
            config:
            - subnet: 192.168.0.0/24
